
server:
  port: 8086

springdoc:
  show-actuator: true
  swagger-ui:
    groups-order: DESC
    disable-swagger-default-url: true
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        security: DEBUG

app:
  cors:
    allowed-origins: http://localhost:3000

spring:
  application:
    name: users-service
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: false
        service-id: config-service
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: moviesdb
      port: 27017
      host: mongodb
      uri: ${DB_URL}
  main:
    allow-circular-references: true

  security:
    oauth2:
      client:
        provider:
          users-service-microservicios:
            issuer-uri: ${KEYCLOAK_URL:http://keycloak:8082/}realms/digital_media
        registration:
          users-service-microservicios:
            provider: users-service-microservicios
            client-id: microservicios
            client-secret: bsFPyChwi3sfCl5Mm00SGckDCKnq3KnQ
            authorization-grant-type: authorization_code
            scope: openid
            redirect-uri: http://localhost:8080/*

users-service-internal:
  serverUrl: ${KEYCLOAK_URL:http://keycloak:8082/}
  realm: digital_media
  clientId: internal
  clientSecret: wejB7agiSI0FjLLIMdxhNlpGjw8PWrXk

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Users Microservice