
spring:
  application:
    name: api-gateway
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-service
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: usersRoute
          uri: lb://users-service
          predicates:
            - Path=/users/**
        - id: moviesRoute
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
  profiles:
    active: dev
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8082/}realms/digital_media
        registration:
          api-gateway-service:
            provider: keycloak-provider
            client-id: api-gateway
            client-secret: iT4iEXwSnkhMurp40yDisffkALANVeMY
            authorization-grant-type: authorization_code
            redirect-uri: 'http://localhost:9090/loguin/oauth2/code/keycloak'

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    enabled: true
